# Kayak

* Voir : https://app.jedha.co/course/project-plan-your-trip-with-kayak-ft/plan-your-trip-with-kayak-ft

In [1]:
# ouvre le fichier hotels_list.json
# construit lune liste start_urls
# start_urls = [
#       #"https://www.booking.com/hotel/fr/ha-tel-marseille-vieux-port.fr.html",
#       #"https://www.booking.com/hotel/fr/hotelkyriadrabatau.fr.html",
#       "https://www.booking.com/hotel/fr/citea-marseille-prado-perier.fr.html",
#     ]
# on veut 

import json

# Ouvrir le fichier JSON et le lire
with open('hotels_list.json', 'r') as f:
    data = json.load(f)

# Initialiser une liste pour stocker les URLs
list_urls = []

# Parcourir les données et extraire les URLs
for entry in data:
    list_urls.append(entry['url'])

# Afficher la liste des URLs
print(list_urls)

['https://www.booking.com/hotel/fr/suite-en-plein-coeur-du-panier-47-vieux-port.fr.html', 'https://www.booking.com/hotel/fr/residence-kley.fr.html', 'https://www.booking.com/hotel/fr/staycity-aparthotels-centre-vieux-port.fr.html', 'https://www.booking.com/hotel/fr/odalys-city-marseille-centre-euromed.fr.html', 'https://www.booking.com/hotel/fr/le-panier-enchante-suites-amp-spa.fr.html', 'https://www.booking.com/hotel/fr/hipark-residences-marseille.fr.html', 'https://www.booking.com/hotel/fr/sweet-design-suite-vieux-port.fr.html', 'https://www.booking.com/hotel/fr/seven-urban-suites.fr.html', 'https://www.booking.com/hotel/fr/hotelkyriadrabatau.fr.html', 'https://www.booking.com/hotel/fr/crowne-plaza-marseille-le-dome.fr.html', 'https://www.booking.com/hotel/fr/lafrenchcasa-canebiere.fr.html', 'https://www.booking.com/hotel/fr/nhow-marseille.fr.html', 'https://www.booking.com/hotel/fr/citadines-aparthotel-marseillepradochanot.fr.html', 'https://www.booking.com/hotel/fr/la-french-casa-noailles.fr.html', 'https://www.booking.com/hotel/fr/le-mistral-marseille.fr.html', 'https://www.booking.com/hotel/fr/appart-fortia.fr.html', 'https://www.booking.com/hotel/fr/votre-adresse-de-charme-hypercentre-marseille.fr.html', 'https://www.booking.com/hotel/fr/air-conditioned-apartment-6min-from-st-charles.fr.html', 'https://www.booking.com/hotel/fr/adagio-city-aparthotel-marseille-saint-charles.fr.html', 'https://www.booking.com/hotel/fr/kyriad-marseille-blancarde-timone.fr.html', 'https://www.booking.com/hotel/fr/citadines-aparthotel-marseilleprado.fr.html', 'https://www.booking.com/hotel/fr/appart-39-odalys-prado-castellane.fr.html', 'https://www.booking.com/hotel/fr/le-grand-prado-marseille.fr.html', 'https://www.booking.com/hotel/fr/ha-tel-marseille-vieux-port.fr.html', 'https://www.booking.com/hotel/fr/citea-marseille-prado-perier.fr.html']

In [1]:
from datetime import datetime, timedelta

aujourdhui = datetime.today()
date_future = aujourdhui + timedelta(days=15)
date_future_str = date_future.strftime('%Y-%m-%d')

# Afficher la date future
print(aujourdhui.strftime('%Y-%m-%d'))
print(date_future_str)

2024-04-07
2024-04-22

In [2]:
# prelude
import pandas as pd
import requests

import my_api_id as key
openweathermap_key = key.openweathermap

In [56]:
ma_liste = [
  "Mont Saint Michel",
  "St Malo",
  "Bayeux",
  "Le Havre",
  "Rouen",
]

# ma_liste = [
#   "Mont Saint Michel",
#   "St Malo",
#   "Bayeux",
#   "Le Havre",
#   "Rouen",
#   "Paris",
#   "Amiens",
#   "Lille",
#   "Strasbourg",
#   "Chateau du Haut Koenigsbourg",
#   "Colmar",
#   "Eguisheim",
#   "Besancon",
#   "Dijon",
#   "Annecy",
#   "Grenoble",
#   "Lyon",
#   "Gorges du Verdon",
#   "Bormes les Mimosas",
#   "Cassis",
#   "Marseille",
#   "Aix en Provence",
#   "Avignon",
#   "Uzes",
#   "Nimes",
#   "Aigues Mortes",
#   "Saintes Maries de la mer",
#   "Collioure",
#   "Carcassonne",
#   "Ariege",
#   "Toulouse",
#   "Montauban",
#   "Biarritz",
#   "Bayonne",
#   "La Rochelle"
# ]

In [4]:
# Testing
url = "https://nominatim.openstreetmap.org/search"

params = {
  "q"       : "Bayonne",
  "format"  : "json",
}

response = requests.get(url, params=params) 
response.json()

# print(response.json()[0]["lat"])
# print(response.json()[0]["lon"])

[{'place_id': 252689850,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 166713,
  'lat': '43.4945144',
  'lon': '-1.4736657',
  'class': 'boundary',
  'type': 'administrative',
  'place_rank': 16,
  'importance': 0.6027800210035323,
  'addresstype': 'town',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Pyrénées-Atlantiques, Nouvelle-Aquitaine, France métropolitaine, 64100, France',
  'boundingbox': ['43.4498733', '43.5188846', '-1.5048438', '-1.4172610']},
 {'place_id': 311414097,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 170504,
  'lat': '40.6687141',
  'lon': '-74.1143091',
  'class': 'boundary',
  'type': 'administrative',
  'place_rank': 16,
  'importance': 0.4914895930584272,
  'addresstype': 'city',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Hudson County, New Jersey, 07002, United States',
  'boundingbox': ['40.6419890', '40.7010720', '-74.1614661', '-74.0495940']},
 {'place_id': 252188442,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 2770753,
  'lat': '43.2775332',
  'lon': '-1.2087111034758713',
  'class': 'boundary',
  'type': 'administrative',
  'place_rank': 14,
  'importance': 0.36895940081389983,
  'addresstype': 'municipality',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Pyrénées-Atlantiques, Nouvelle-Aquitaine, France métropolitaine, France',
  'boundingbox': ['43.0076101', '43.5474276', '-1.7910227', '-0.8973720']},
 {'place_id': 72184433,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 2387259037,
  'lat': '43.8909989',
  'lon': '2.1101285',
  'class': 'place',
  'type': 'hamlet',
  'place_rank': 20,
  'importance': 0.25000999999999995,
  'addresstype': 'hamlet',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Carlus, Albi, Tarn, Occitanie, France métropolitaine, 81990, France',
  'boundingbox': ['43.8709989', '43.9109989', '2.0901285', '2.1301285']},
 {'place_id': 73983768,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 1846698959,
  'lat': '44.438205',
  'lon': '4.8883211',
  'class': 'place',
  'type': 'hamlet',
  'place_rank': 20,
  'importance': 0.25000999999999995,
  'addresstype': 'hamlet',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Grignan, Nyons, Drôme, Auvergne-Rhône-Alpes, France métropolitaine, 26230, France',
  'boundingbox': ['44.4182050', '44.4582050', '4.8683211', '4.9083211']},
 {'place_id': 285439851,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 151892641,
  'lat': '42.7855546',
  'lon': '-101.9776601',
  'class': 'place',
  'type': 'hamlet',
  'place_rank': 20,
  'importance': 0.25000999999999995,
  'addresstype': 'hamlet',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Cherry County, Nebraska, United States',
  'boundingbox': ['42.7655546', '42.8055546', '-101.9976601', '-101.9576601']},
 {'place_id': 72706104,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 4407040041,
  'lat': '44.6419992',
  'lon': '0.7585094',
  'class': 'place',
  'type': 'hamlet',
  'place_rank': 20,
  'importance': 0.25000999999999995,
  'addresstype': 'hamlet',
  'name': 'Bayonne',
  'display_name': 'Bayonne, Parisot, Villeréal, Villeneuve-sur-Lot, Lot-et-Garonne, Nouvelle-Aquitaine, France métropolitaine, 47210, France',
  'boundingbox': ['44.6219992', '44.6619992', '0.7385094', '0.7785094']}]

In [60]:
# Testing
for ville in ma_liste:
  print(ville)
# url = "https://nominatim.openstreetmap.org/search"

# params = {
#   "q"       : "Bayonne",
#   "format"  : "json",
# }

# response = requests.get(url, params=params) 

# print(response.json()[0]["lat"])
# print(response.json()[0]["lon"])

Mont Saint Michel
St Malo
Bayeux
Le Havre
Rouen

In [127]:
df = pd.DataFrame(columns=["site", "latitude", "longitude"])
df

Empty DataFrame
Columns: [site, latitude, longitude]
Index: []

In [128]:

url = "https://nominatim.openstreetmap.org/search"

for site in ma_liste:
  params = {
    "q" : site,
    "format":"json",
  }
  response = requests.get(url, params=params) 
  list_tmp = [site, response.json()[0]["lat"], response.json()[0]["lon"]]
  df.loc[len(df)] = list_tmp

df

                site    latitude           longitude
0  Mont Saint Michel  48.6359541  -1.511459954959514
1            St Malo   49.314695         -96.9538228
2             Bayeux  49.2764624          -0.7024738
3           Le Havre  49.4938975           0.1079732
4              Rouen  49.4404591           1.0939658

In [28]:
# Testing


url = "http://api.openweathermap.org/data/2.5/forecast"

params = {
  "q" : "Bayonne,fr",
  "appid" : openweathermap_key
}

response = requests.get(url, params=params) 
response.json()

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1711692000,
   'main': {'temp': 287.09,
    'feels_like': 286.42,
    'temp_min': 284.81,
    'temp_max': 287.09,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 968,
    'humidity': 72,
    'temp_kf': 2.28},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2, 'deg': 290, 'gust': 3.73},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 2.28},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 06:00:00'},
  {'dt': 1711702800,
   'main': {'temp': 286.03,
    'feels_like': 285.44,
    'temp_min': 283.9,
    'temp_max': 286.03,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 970,
    'humidity': 79,
    'temp_kf': 2.13},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.2, 'deg': 321, 'gust': 2.21},
   'visibility': 10000,
   'pop': 0.95,
   'rain': {'3h': 1.09},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 09:00:00'},
  {'dt': 1711713600,
   'main': {'temp': 284.64,
    'feels_like': 284.09,
    'temp_min': 283.41,
    'temp_max': 284.64,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 970,
    'humidity': 86,
    'temp_kf': 1.23},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.95, 'deg': 31, 'gust': 1.08},
   'visibility': 3044,
   'pop': 0.98,
   'rain': {'3h': 0.54},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 12:00:00'},
  {'dt': 1711724400,
   'main': {'temp': 281.82,
    'feels_like': 281.27,
    'temp_min': 281.82,
    'temp_max': 281.82,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 501,
     'main': 'Rain',
     'description': 'moderate rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.51, 'deg': 323, 'gust': 2.08},
   'visibility': 1000,
   'pop': 1,
   'rain': {'3h': 10.72},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 15:00:00'},
  {'dt': 1711735200,
   'main': {'temp': 280.35,
    'feels_like': 279.31,
    'temp_min': 280.35,
    'temp_max': 280.35,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 967,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.77, 'deg': 284, 'gust': 3.83},
   'visibility': 670,
   'pop': 1,
   'rain': {'3h': 20.29},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 18:00:00'},
  {'dt': 1711746000,
   'main': {'temp': 278.46,
    'feels_like': 278.46,
    'temp_min': 278.46,
    'temp_max': 278.46,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 970,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.25, 'deg': 189, 'gust': 2.2},
   'visibility': 4533,
   'pop': 1,
   'rain': {'3h': 12.55},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-29 21:00:00'},
  {'dt': 1711756800,
   'main': {'temp': 279.45,
    'feels_like': 279.45,
    'temp_min': 279.45,
    'temp_max': 279.45,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 971,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.14, 'deg': 205, 'gust': 2.46},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.67},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 00:00:00'},
  {'dt': 1711767600,
   'main': {'temp': 279.79,
    'feels_like': 279.07,
    'temp_min': 279.79,
    'temp_max': 279.79,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 970,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.42, 'deg': 140, 'gust': 2.19},
   'visibility': 10000,
   'pop': 0.35,
   'rain': {'3h': 0.27},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 03:00:00'},
  {'dt': 1711778400,
   'main': {'temp': 277.79,
    'feels_like': 275.82,
    'temp_min': 277.79,
    'temp_max': 277.79,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 66},
   'wind': {'speed': 2.28, 'deg': 159, 'gust': 3.62},
   'visibility': 10000,
   'pop': 0.02,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 06:00:00'},
  {'dt': 1711789200,
   'main': {'temp': 283.49,
    'feels_like': 282.69,
    'temp_min': 283.49,
    'temp_max': 283.49,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 74},
   'wind': {'speed': 2.61, 'deg': 169, 'gust': 7.48},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 09:00:00'},
  {'dt': 1711800000,
   'main': {'temp': 287.17,
    'feels_like': 286.17,
    'temp_min': 287.17,
    'temp_max': 287.17,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 968,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 85},
   'wind': {'speed': 4.07, 'deg': 171, 'gust': 7.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 12:00:00'},
  {'dt': 1711810800,
   'main': {'temp': 287.82,
    'feels_like': 286.86,
    'temp_min': 287.82,
    'temp_max': 287.82,
    'pressure': 993,
    'sea_level': 993,
    'grnd_level': 966,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 77},
   'wind': {'speed': 3.57, 'deg': 169, 'gust': 9.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 15:00:00'},
  {'dt': 1711821600,
   'main': {'temp': 283.95,
    'feels_like': 283.2,
    'temp_min': 283.95,
    'temp_max': 283.95,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 83},
   'wind': {'speed': 2.39, 'deg': 144, 'gust': 3.12},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 18:00:00'},
  {'dt': 1711832400,
   'main': {'temp': 281.25,
    'feels_like': 279.54,
    'temp_min': 281.25,
    'temp_max': 281.25,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.75, 'deg': 166, 'gust': 3.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 21:00:00'},
  {'dt': 1711843200,
   'main': {'temp': 281.16,
    'feels_like': 279.56,
    'temp_min': 281.16,
    'temp_max': 281.16,
    'pressure': 993,
    'sea_level': 993,
    'grnd_level': 966,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 2.58, 'deg': 161, 'gust': 7.03},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 00:00:00'},
  {'dt': 1711854000,
   'main': {'temp': 281.1,
    'feels_like': 279.69,
    'temp_min': 281.1,
    'temp_max': 281.1,
    'pressure': 992,
    'sea_level': 992,
    'grnd_level': 964,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 91},
   'wind': {'speed': 2.31, 'deg': 141, 'gust': 4.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 03:00:00'},
  {'dt': 1711864800,
   'main': {'temp': 282.37,
    'feels_like': 280.8,
    'temp_min': 282.37,
    'temp_max': 282.37,
    'pressure': 989,
    'sea_level': 989,
    'grnd_level': 962,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 89},
   'wind': {'speed': 2.87, 'deg': 130, 'gust': 8.25},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 06:00:00'},
  {'dt': 1711875600,
   'main': {'temp': 284.02,
    'feels_like': 283.25,
    'temp_min': 284.02,
    'temp_max': 284.02,
    'pressure': 988,
    'sea_level': 988,
    'grnd_level': 961,
    'humidity': 80,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.61, 'deg': 174, 'gust': 21.04},
   'visibility': 10000,
   'pop': 0.96,
   'rain': {'3h': 1.64},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 09:00:00'},
  {'dt': 1711886400,
   'main': {'temp': 287.31,
    'feels_like': 286.53,
    'temp_min': 287.31,
    'temp_max': 287.31,
    'pressure': 990,
    'sea_level': 990,
    'grnd_level': 963,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 84},
   'wind': {'speed': 6.51, 'deg': 204, 'gust': 16.14},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 1.73},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 12:00:00'},
  {'dt': 1711897200,
   'main': {'temp': 283.32,
    'feels_like': 282.64,
    'temp_min': 283.32,
    'temp_max': 283.32,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 67},
   'wind': {'speed': 6.17, 'deg': 281, 'gust': 12.5},
   'visibility': 8604,
   'pop': 1,
   'rain': {'3h': 1.42},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 15:00:00'},
  {'dt': 1711908000,
   'main': {'temp': 283.25,
    'feels_like': 282.54,
    'temp_min': 283.25,
    'temp_max': 283.25,
    'pressure': 997,
    'sea_level': 997,
    'grnd_level': 970,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 2.62, 'deg': 251, 'gust': 5.35},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.89},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 18:00:00'},
  {'dt': 1711918800,
   'main': {'temp': 281.94,
    'feels_like': 280.13,
    'temp_min': 281.94,
    'temp_max': 281.94,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 973,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 83},
   'wind': {'speed': 3.13, 'deg': 220, 'gust': 8.89},
   'visibility': 10000,
   'pop': 0.69,
   'rain': {'3h': 0.38},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 21:00:00'},
  {'dt': 1711929600,
   'main': {'temp': 280.11,
    'feels_like': 277.8,
    'temp_min': 280.11,
    'temp_max': 280.11,
    'pressure': 1003,
    'sea_level': 1003,
    'grnd_level': 975,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 62},
   'wind': {'speed': 3.33, 'deg': 211, 'gust': 7.51},
   'visibility': 10000,
   'pop': 0.21,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 00:00:00'},
  {'dt': 1711940400,
   'main': {'temp': 279.8,
    'feels_like': 277.88,
    'temp_min': 279.8,
    'temp_max': 279.8,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 977,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 24},
   'wind': {'speed': 2.66, 'deg': 206, 'gust': 3.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 03:00:00'},
  {'dt': 1711951200,
   'main': {'temp': 279.52,
    'feels_like': 277.61,
    'temp_min': 279.52,
    'temp_max': 279.52,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 979,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 49},
   'wind': {'speed': 2.58, 'deg': 200, 'gust': 4.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 06:00:00'},
  {'dt': 1711962000,
   'main': {'temp': 285.94,
    'feels_like': 284.74,
    'temp_min': 285.94,
    'temp_max': 285.94,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 981,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 17},
   'wind': {'speed': 4.44, 'deg': 228, 'gust': 11.98},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 09:00:00'},
  {'dt': 1711972800,
   'main': {'temp': 286.77,
    'feels_like': 285.81,
    'temp_min': 286.77,
    'temp_max': 286.77,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 983,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 31},
   'wind': {'speed': 6.33, 'deg': 250, 'gust': 10.22},
   'visibility': 10000,
   'pop': 0.68,
   'rain': {'3h': 0.7},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 12:00:00'},
  {'dt': 1711983600,
   'main': {'temp': 288.22,
    'feels_like': 287.04,
    'temp_min': 288.22,
    'temp_max': 288.22,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 984,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 27},
   'wind': {'speed': 2.94, 'deg': 307, 'gust': 5.51},
   'visibility': 10000,
   'pop': 0.75,
   'rain': {'3h': 0.63},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 15:00:00'},
  {'dt': 1711994400,
   'main': {'temp': 283.4,
    'feels_like': 282.6,
    'temp_min': 283.4,
    'temp_max': 283.4,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 987,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 37},
   'wind': {'speed': 1.14, 'deg': 281, 'gust': 1.52},
   'visibility': 10000,
   'pop': 0.77,
   'rain': {'3h': 0.69},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 18:00:00'},
  {'dt': 1712005200,
   'main': {'temp': 280.9,
    'feels_like': 279.77,
    'temp_min': 280.9,
    'temp_max': 280.9,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 990,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 37},
   'wind': {'speed': 1.95, 'deg': 190, 'gust': 1.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 21:00:00'},
  {'dt': 1712016000,
   'main': {'temp': 279.69,
    'feels_like': 278.14,
    'temp_min': 279.69,
    'temp_max': 279.69,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 42},
   'wind': {'speed': 2.19, 'deg': 177, 'gust': 1.98},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-02 00:00:00'},
  {'dt': 1712026800,
   'main': {'temp': 279.45,
    'feels_like': 277.74,
    'temp_min': 279.45,
    'temp_max': 279.45,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 71},
   'wind': {'speed': 2.32, 'deg': 186, 'gust': 2.43},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-02 03:00:00'},
  {'dt': 1712037600,
   'main': {'temp': 279.46,
    'feels_like': 277.59,
    'temp_min': 279.46,
    'temp_max': 279.46,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 57},
   'wind': {'speed': 2.51, 'deg': 184, 'gust': 3.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 06:00:00'},
  {'dt': 1712048400,
   'main': {'temp': 287.17,
    'feels_like': 286.22,
    'temp_min': 287.17,
    'temp_max': 287.17,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 991,
    'humidity': 61,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.09, 'deg': 179, 'gust': 3.91},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 09:00:00'},
  {'dt': 1712059200,
   'main': {'temp': 290.49,
    'feels_like': 289.53,
    'temp_min': 290.49,
    'temp_max': 290.49,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 989,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.7, 'deg': 202, 'gust': 7.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 12:00:00'},
  {'dt': 1712070000,
   'main': {'temp': 289.41,
    'feels_like': 288.58,
    'temp_min': 289.41,
    'temp_max': 289.41,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 988,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.15, 'deg': 211, 'gust': 8.44},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 15:00:00'},
  {'dt': 1712080800,
   'main': {'temp': 287.06,
    'feels_like': 286.36,
    'temp_min': 287.06,
    'temp_max': 287.06,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 987,
    'humidity': 71,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.19, 'deg': 209, 'gust': 3.28},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 18:00:00'},
  {'dt': 1712091600,
   'main': {'temp': 284.7,
    'feels_like': 284.21,
    'temp_min': 284.7,
    'temp_max': 284.7,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 988,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.44, 'deg': 187, 'gust': 4.12},
   'visibility': 10000,
   'pop': 0.39,

In [29]:

# Testing

url = "http://api.openweathermap.org/data/2.5/forecast"

# Bayonne
params = {
  "lat" : "43.3333",
  "lon" : "-1.4167",
  "appid" : openweathermap_key,
}

response = requests.get(url, params=params) 
response.json()

# print(response.json()[0]["lat"])
# print(response.json()[0]["lon"])

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1711692000,
   'main': {'temp': 287.09,
    'feels_like': 286.42,
    'temp_min': 284.81,
    'temp_max': 287.09,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 968,
    'humidity': 72,
    'temp_kf': 2.28},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2, 'deg': 290, 'gust': 3.73},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 2.28},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 06:00:00'},
  {'dt': 1711702800,
   'main': {'temp': 286.03,
    'feels_like': 285.44,
    'temp_min': 283.9,
    'temp_max': 286.03,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 970,
    'humidity': 79,
    'temp_kf': 2.13},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.2, 'deg': 321, 'gust': 2.21},
   'visibility': 10000,
   'pop': 0.95,
   'rain': {'3h': 1.09},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 09:00:00'},
  {'dt': 1711713600,
   'main': {'temp': 284.64,
    'feels_like': 284.09,
    'temp_min': 283.41,
    'temp_max': 284.64,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 970,
    'humidity': 86,
    'temp_kf': 1.23},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.95, 'deg': 31, 'gust': 1.08},
   'visibility': 3044,
   'pop': 0.98,
   'rain': {'3h': 0.54},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 12:00:00'},
  {'dt': 1711724400,
   'main': {'temp': 281.82,
    'feels_like': 281.27,
    'temp_min': 281.82,
    'temp_max': 281.82,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 501,
     'main': 'Rain',
     'description': 'moderate rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.51, 'deg': 323, 'gust': 2.08},
   'visibility': 1000,
   'pop': 1,
   'rain': {'3h': 10.72},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 15:00:00'},
  {'dt': 1711735200,
   'main': {'temp': 280.35,
    'feels_like': 279.31,
    'temp_min': 280.35,
    'temp_max': 280.35,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 967,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.77, 'deg': 284, 'gust': 3.83},
   'visibility': 670,
   'pop': 1,
   'rain': {'3h': 20.29},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-29 18:00:00'},
  {'dt': 1711746000,
   'main': {'temp': 278.46,
    'feels_like': 278.46,
    'temp_min': 278.46,
    'temp_max': 278.46,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 970,
    'humidity': 98,
    'temp_kf': 0},
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.25, 'deg': 189, 'gust': 2.2},
   'visibility': 4533,
   'pop': 1,
   'rain': {'3h': 12.55},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-29 21:00:00'},
  {'dt': 1711756800,
   'main': {'temp': 279.45,
    'feels_like': 279.45,
    'temp_min': 279.45,
    'temp_max': 279.45,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 971,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.14, 'deg': 205, 'gust': 2.46},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.67},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 00:00:00'},
  {'dt': 1711767600,
   'main': {'temp': 279.79,
    'feels_like': 279.07,
    'temp_min': 279.79,
    'temp_max': 279.79,
    'pressure': 998,
    'sea_level': 998,
    'grnd_level': 970,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.42, 'deg': 140, 'gust': 2.19},
   'visibility': 10000,
   'pop': 0.35,
   'rain': {'3h': 0.27},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 03:00:00'},
  {'dt': 1711778400,
   'main': {'temp': 277.79,
    'feels_like': 275.82,
    'temp_min': 277.79,
    'temp_max': 277.79,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 96,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 66},
   'wind': {'speed': 2.28, 'deg': 159, 'gust': 3.62},
   'visibility': 10000,
   'pop': 0.02,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 06:00:00'},
  {'dt': 1711789200,
   'main': {'temp': 283.49,
    'feels_like': 282.69,
    'temp_min': 283.49,
    'temp_max': 283.49,
    'pressure': 996,
    'sea_level': 996,
    'grnd_level': 968,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 74},
   'wind': {'speed': 2.61, 'deg': 169, 'gust': 7.48},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 09:00:00'},
  {'dt': 1711800000,
   'main': {'temp': 287.17,
    'feels_like': 286.17,
    'temp_min': 287.17,
    'temp_max': 287.17,
    'pressure': 995,
    'sea_level': 995,
    'grnd_level': 968,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 85},
   'wind': {'speed': 4.07, 'deg': 171, 'gust': 7.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 12:00:00'},
  {'dt': 1711810800,
   'main': {'temp': 287.82,
    'feels_like': 286.86,
    'temp_min': 287.82,
    'temp_max': 287.82,
    'pressure': 993,
    'sea_level': 993,
    'grnd_level': 966,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 77},
   'wind': {'speed': 3.57, 'deg': 169, 'gust': 9.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 15:00:00'},
  {'dt': 1711821600,
   'main': {'temp': 283.95,
    'feels_like': 283.2,
    'temp_min': 283.95,
    'temp_max': 283.95,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 83},
   'wind': {'speed': 2.39, 'deg': 144, 'gust': 3.12},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-30 18:00:00'},
  {'dt': 1711832400,
   'main': {'temp': 281.25,
    'feels_like': 279.54,
    'temp_min': 281.25,
    'temp_max': 281.25,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.75, 'deg': 166, 'gust': 3.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-30 21:00:00'},
  {'dt': 1711843200,
   'main': {'temp': 281.16,
    'feels_like': 279.56,
    'temp_min': 281.16,
    'temp_max': 281.16,
    'pressure': 993,
    'sea_level': 993,
    'grnd_level': 966,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 2.58, 'deg': 161, 'gust': 7.03},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 00:00:00'},
  {'dt': 1711854000,
   'main': {'temp': 281.1,
    'feels_like': 279.69,
    'temp_min': 281.1,
    'temp_max': 281.1,
    'pressure': 992,
    'sea_level': 992,
    'grnd_level': 964,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 91},
   'wind': {'speed': 2.31, 'deg': 141, 'gust': 4.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 03:00:00'},
  {'dt': 1711864800,
   'main': {'temp': 282.37,
    'feels_like': 280.8,
    'temp_min': 282.37,
    'temp_max': 282.37,
    'pressure': 989,
    'sea_level': 989,
    'grnd_level': 962,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 89},
   'wind': {'speed': 2.87, 'deg': 130, 'gust': 8.25},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 06:00:00'},
  {'dt': 1711875600,
   'main': {'temp': 284.02,
    'feels_like': 283.25,
    'temp_min': 284.02,
    'temp_max': 284.02,
    'pressure': 988,
    'sea_level': 988,
    'grnd_level': 961,
    'humidity': 80,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.61, 'deg': 174, 'gust': 21.04},
   'visibility': 10000,
   'pop': 0.96,
   'rain': {'3h': 1.64},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 09:00:00'},
  {'dt': 1711886400,
   'main': {'temp': 287.31,
    'feels_like': 286.53,
    'temp_min': 287.31,
    'temp_max': 287.31,
    'pressure': 990,
    'sea_level': 990,
    'grnd_level': 963,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 84},
   'wind': {'speed': 6.51, 'deg': 204, 'gust': 16.14},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 1.73},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 12:00:00'},
  {'dt': 1711897200,
   'main': {'temp': 283.32,
    'feels_like': 282.64,
    'temp_min': 283.32,
    'temp_max': 283.32,
    'pressure': 994,
    'sea_level': 994,
    'grnd_level': 967,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 67},
   'wind': {'speed': 6.17, 'deg': 281, 'gust': 12.5},
   'visibility': 8604,
   'pop': 1,
   'rain': {'3h': 1.42},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 15:00:00'},
  {'dt': 1711908000,
   'main': {'temp': 283.25,
    'feels_like': 282.54,
    'temp_min': 283.25,
    'temp_max': 283.25,
    'pressure': 997,
    'sea_level': 997,
    'grnd_level': 970,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 2.62, 'deg': 251, 'gust': 5.35},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.89},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-03-31 18:00:00'},
  {'dt': 1711918800,
   'main': {'temp': 281.94,
    'feels_like': 280.13,
    'temp_min': 281.94,
    'temp_max': 281.94,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 973,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 83},
   'wind': {'speed': 3.13, 'deg': 220, 'gust': 8.89},
   'visibility': 10000,
   'pop': 0.69,
   'rain': {'3h': 0.38},
   'sys': {'pod': 'n'},
   'dt_txt': '2024-03-31 21:00:00'},
  {'dt': 1711929600,
   'main': {'temp': 280.11,
    'feels_like': 277.8,
    'temp_min': 280.11,
    'temp_max': 280.11,
    'pressure': 1003,
    'sea_level': 1003,
    'grnd_level': 975,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 62},
   'wind': {'speed': 3.33, 'deg': 211, 'gust': 7.51},
   'visibility': 10000,
   'pop': 0.21,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 00:00:00'},
  {'dt': 1711940400,
   'main': {'temp': 279.8,
    'feels_like': 277.88,
    'temp_min': 279.8,
    'temp_max': 279.8,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 977,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 24},
   'wind': {'speed': 2.66, 'deg': 206, 'gust': 3.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 03:00:00'},
  {'dt': 1711951200,
   'main': {'temp': 279.52,
    'feels_like': 277.61,
    'temp_min': 279.52,
    'temp_max': 279.52,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 979,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 49},
   'wind': {'speed': 2.58, 'deg': 200, 'gust': 4.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 06:00:00'},
  {'dt': 1711962000,
   'main': {'temp': 285.94,
    'feels_like': 284.74,
    'temp_min': 285.94,
    'temp_max': 285.94,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 981,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 17},
   'wind': {'speed': 4.44, 'deg': 228, 'gust': 11.98},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 09:00:00'},
  {'dt': 1711972800,
   'main': {'temp': 286.77,
    'feels_like': 285.81,
    'temp_min': 286.77,
    'temp_max': 286.77,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 983,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 31},
   'wind': {'speed': 6.33, 'deg': 250, 'gust': 10.22},
   'visibility': 10000,
   'pop': 0.68,
   'rain': {'3h': 0.7},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 12:00:00'},
  {'dt': 1711983600,
   'main': {'temp': 288.22,
    'feels_like': 287.04,
    'temp_min': 288.22,
    'temp_max': 288.22,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 984,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 27},
   'wind': {'speed': 2.94, 'deg': 307, 'gust': 5.51},
   'visibility': 10000,
   'pop': 0.75,
   'rain': {'3h': 0.63},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 15:00:00'},
  {'dt': 1711994400,
   'main': {'temp': 283.4,
    'feels_like': 282.6,
    'temp_min': 283.4,
    'temp_max': 283.4,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 987,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 37},
   'wind': {'speed': 1.14, 'deg': 281, 'gust': 1.52},
   'visibility': 10000,
   'pop': 0.77,
   'rain': {'3h': 0.69},
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-01 18:00:00'},
  {'dt': 1712005200,
   'main': {'temp': 280.9,
    'feels_like': 279.77,
    'temp_min': 280.9,
    'temp_max': 280.9,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 990,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 37},
   'wind': {'speed': 1.95, 'deg': 190, 'gust': 1.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-01 21:00:00'},
  {'dt': 1712016000,
   'main': {'temp': 279.69,
    'feels_like': 278.14,
    'temp_min': 279.69,
    'temp_max': 279.69,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 42},
   'wind': {'speed': 2.19, 'deg': 177, 'gust': 1.98},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-02 00:00:00'},
  {'dt': 1712026800,
   'main': {'temp': 279.45,
    'feels_like': 277.74,
    'temp_min': 279.45,
    'temp_max': 279.45,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 71},
   'wind': {'speed': 2.32, 'deg': 186, 'gust': 2.43},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2024-04-02 03:00:00'},
  {'dt': 1712037600,
   'main': {'temp': 279.46,
    'feels_like': 277.59,
    'temp_min': 279.46,
    'temp_max': 279.46,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 991,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 57},
   'wind': {'speed': 2.51, 'deg': 184, 'gust': 3.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 06:00:00'},
  {'dt': 1712048400,
   'main': {'temp': 287.17,
    'feels_like': 286.22,
    'temp_min': 287.17,
    'temp_max': 287.17,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 991,
    'humidity': 61,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.09, 'deg': 179, 'gust': 3.91},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 09:00:00'},
  {'dt': 1712059200,
   'main': {'temp': 290.49,
    'feels_like': 289.53,
    'temp_min': 290.49,
    'temp_max': 290.49,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 989,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.7, 'deg': 202, 'gust': 7.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 12:00:00'},
  {'dt': 1712070000,
   'main': {'temp': 289.41,
    'feels_like': 288.58,
    'temp_min': 289.41,
    'temp_max': 289.41,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 988,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.15, 'deg': 211, 'gust': 8.44},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 15:00:00'},
  {'dt': 1712080800,
   'main': {'temp': 287.06,
    'feels_like': 286.36,
    'temp_min': 287.06,
    'temp_max': 287.06,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 987,
    'humidity': 71,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.19, 'deg': 209, 'gust': 3.28},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2024-04-02 18:00:00'},
  {'dt': 1712091600,
   'main': {'temp': 284.7,
    'feels_like': 284.21,
    'temp_min': 284.7,
    'temp_max': 284.7,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 988,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.44, 'deg': 187, 'gust': 4.12},
   'visibility': 10000,
   'pop': 0.39,

In [38]:
# https://medium.com/towards-data-science/all-pandas-json-normalize-you-should-know-for-flattening-json-13eae1dfb7dd
df_tmp = pd.json_normalize(response.json(), max_level=1)
display(df_tmp)

,cod,message,cnt,list,city.id,city.name,city.coord,city.country,city.population,city.timezone,city.sunrise,city.sunset
0,200,0,40,"[{'dt': 1711692000, 'main': {'temp': 287.09, '...",3034473,Arrondissement de Bayonne,"{'lat': 43.3333, 'lon': -1.4167}",FR,268739,3600,1711691531,1711736892

In [40]:
df_tmp = pd.json_normalize(response.json(), max_level=2)
display(df_tmp)

,cod,message,cnt,list,city.id,city.name,city.coord.lat,city.coord.lon,city.country,city.population,city.timezone,city.sunrise,city.sunset
0,200,0,40,"[{'dt': 1711692000, 'main': {'temp': 287.09, '...",3034473,Arrondissement de Bayonne,43.3333,-1.4167,FR,268739,3600,1711691531,1711736892

In [54]:
df_tmp = pd.json_normalize(response.json()["list"], record_path=["weather"])
# df_tmp = df_tmp.transpose()
display(df_tmp)

     id    main           description icon
0   500    Rain            light rain  10d
1   500    Rain            light rain  10d
2   500    Rain            light rain  10d
3   501    Rain         moderate rain  10d
4   502    Rain  heavy intensity rain  10d
5   502    Rain  heavy intensity rain  10n
6   500    Rain            light rain  10n
7   500    Rain            light rain  10n
8   803  Clouds         broken clouds  04d
9   803  Clouds         broken clouds  04d
10  804  Clouds       overcast clouds  04d
11  803  Clouds         broken clouds  04d
12  803  Clouds         broken clouds  04d
13  804  Clouds       overcast clouds  04n
14  804  Clouds       overcast clouds  04n
15  804  Clouds       overcast clouds  04n
16  804  Clouds       overcast clouds  04d
17  500    Rain            light rain  10d
18  500    Rain            light rain  10d
19  500    Rain            light rain  10d
20  500    Rain            light rain  10d
21  500    Rain            light rain  10n
22  803  Clouds         broken clouds  04n
23  801  Clouds            few clouds  02n
24  802  Clouds      scattered clouds  03d
25  801  Clouds            few clouds  02d
26  500    Rain            light rain  10d
27  500    Rain            light rain  10d
28  500    Rain            light rain  10d
29  802  Clouds      scattered clouds  03n
30  802  Clouds      scattered clouds  03n
31  803  Clouds         broken clouds  04n
32  803  Clouds         broken clouds  04d
33  804  Clouds       overcast clouds  04d
34  804  Clouds       overcast clouds  04d
35  804  Clouds       overcast clouds  04d
36  804  Clouds       overcast clouds  04d
37  500    Rain            light rain  10n
38  804  Clouds       overcast clouds  04n
39  803  Clouds         broken clouds  04n

In [49]:
df_tmp = pd.json_normalize(response.json(), record_path=["list"])
display(df_tmp)

,dt,weather,visibility,pop,dt_txt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.sea_level,main.grnd_level,main.humidity,main.temp_kf,clouds.all,wind.speed,wind.deg,wind.gust,rain.3h,sys.pod
0,1711692000,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2024-03-29 06:00:00,287.09,286.42,284.81,287.09,994,994,968,72,2.28,100,2.00,290,3.73,2.28,d
1,1711702800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.95,2024-03-29 09:00:00,286.03,285.44,283.90,286.03,995,995,970,79,2.13,100,2.20,321,2.21,1.09,d
2,1711713600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",3044,0.98,2024-03-29 12:00:00,284.64,284.09,283.41,284.64,996,996,970,86,1.23,100,1.95,31,1.08,0.54,d
3,1711724400,"[{'id': 501, 'main': 'Rain', 'description': 'm...",1000,1.00,2024-03-29 15:00:00,281.82,281.27,281.82,281.82,996,996,968,98,0.00,100,1.51,323,2.08,10.72,d
4,1711735200,"[{'id': 502, 'main': 'Rain', 'description': 'h...",670,1.00,2024-03-29 18:00:00,280.35,279.31,280.35,280.35,995,995,967,98,0.00,100,1.77,284,3.83,20.29,d
5,1711746000,"[{'id': 502, 'main': 'Rain', 'description': 'h...",4533,1.00,2024-03-29 21:00:00,278.46,278.46,278.46,278.46,998,998,970,98,0.00,100,1.25,189,2.20,12.55,n
6,1711756800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2024-03-30 00:00:00,279.45,279.45,279.45,279.45,998,998,971,96,0.00,100,1.14,205,2.46,0.67,n
7,1711767600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.35,2024-03-30 03:00:00,279.79,279.07,279.79,279.79,998,998,970,96,0.00,100,1.42,140,2.19,0.27,n
8,1711778400,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.02,2024-03-30 06:00:00,277.79,275.82,277.79,277.79,996,996,968,96,0.00,66,2.28,159,3.62,NaN,d
9,1711789200,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-30 09:00:00,283.49,282.69,283.49,283.49,996,996,968,81,0.00,74,2.61,169,7.48,NaN,d
10,1711800000,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-30 12:00:00,287.17,286.17,287.17,287.17,995,995,968,59,0.00,85,4.07,171,7.93,NaN,d
11,1711810800,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-30 15:00:00,287.82,286.86,287.82,287.82,993,993,966,58,0.00,77,3.57,169,9.02,NaN,d
12,1711821600,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-30 18:00:00,283.95,283.20,283.95,283.95,994,994,967,81,0.00,83,2.39,144,3.12,NaN,d
13,1711832400,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-30 21:00:00,281.25,279.54,281.25,281.25,994,994,967,88,0.00,97,2.75,166,3.67,NaN,n
14,1711843200,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-31 00:00:00,281.16,279.56,281.16,281.16,993,993,966,85,0.00,96,2.58,161,7.03,NaN,n
15,1711854000,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-31 03:00:00,281.10,279.69,281.10,281.10,992,992,964,87,0.00,91,2.31,141,4.96,NaN,n
16,1711864800,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-03-31 06:00:00,282.37,280.80,282.37,282.37,989,989,962,78,0.00,89,2.87,130,8.25,NaN,d
17,1711875600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.96,2024-03-31 09:00:00,284.02,283.25,284.02,284.02,988,988,961,80,0.00,100,5.61,174,21.04,1.64,d
18,1711886400,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2024-03-31 12:00:00,287.31,286.53,287.31,287.31,990,990,963,67,0.00,84,6.51,204,16.14,1.73,d
19,1711897200,"[{'id': 500, 'main': 'Rain', 'description': 'l...",8604,1.00,2024-03-31 15:00:00,283.32,282.64,283.32,283.32,994,994,967,86,0.00,67,6.17,281,12.50,1.42,d
20,1711908000,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2024-03-31 18:00:00,283.25,282.54,283.25,283.25,997,997,970,85,0.00,86,2.62,251,5.35,0.89,d
21,1711918800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.69,2024-03-31 21:00:00,281.94,280.13,281.94,281.94,1000,1000,973,85,0.00,83,3.13,220,8.89,0.38,n
22,1711929600,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.21,2024-04-01 00:00:00,280.11,277.80,280.11,280.11,1003,1003,975,85,0.00,62,3.33,211,7.51,NaN,n
23,1711940400,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-01 03:00:00,279.80,277.88,279.80,279.80,1005,1005,977,85,0.00,24,2.66,206,3.74,NaN,n
24,1711951200,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-01 06:00:00,279.52,277.61,279.52,279.52,1006,1006,979,83,0.00,49,2.58,200,4.83,NaN,d
25,1711962000,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-01 09:00:00,285.94,284.74,285.94,285.94,1008,1008,981,56,0.00,17,4.44,228,11.98,NaN,d
26,1711972800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.68,2024-04-01 12:00:00,286.77,285.81,286.77,286.77,1010,1010,983,62,0.00,31,6.33,250,10.22,0.70,d
27,1711983600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.75,2024-04-01 15:00:00,288.22,287.04,288.22,288.22,1011,1011,984,48,0.00,27,2.94,307,5.51,0.63,d
28,1711994400,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.77,2024-04-01 18:00:00,283.40,282.60,283.40,283.40,1015,1015,987,81,0.00,37,1.14,281,1.52,0.69,d
29,1712005200,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-01 21:00:00,280.90,279.77,280.90,280.90,1018,1018,990,86,0.00,37,1.95,190,1.62,NaN,n
30,1712016000,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 00:00:00,279.69,278.14,279.69,279.69,1019,1019,991,87,0.00,42,2.19,177,1.98,NaN,n
31,1712026800,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 03:00:00,279.45,277.74,279.45,279.45,1019,1019,991,87,0.00,71,2.32,186,2.43,NaN,n
32,1712037600,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 06:00:00,279.46,277.59,279.46,279.46,1019,1019,991,87,0.00,57,2.51,184,3.26,NaN,d
33,1712048400,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 09:00:00,287.17,286.22,287.17,287.17,1018,1018,991,61,0.00,100,2.09,179,3.91,NaN,d
34,1712059200,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 12:00:00,290.49,289.53,290.49,290.49,1016,1016,989,48,0.00,100,3.70,202,7.94,NaN,d
35,1712070000,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 15:00:00,289.41,288.58,289.41,289.41,1015,1015,988,57,0.00,100,3.15,211,8.44,NaN,d
36,1712080800,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-02 18:00:00,287.06,286.36,287.06,287.06,1015,1015,987,71,0.00,100,2.19,209,3.28,NaN,d
37,1712091600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.39,2024-04-02 21:00:00,284.70,284.21,284.70,284.70,1015,1015,988,88,0.00,100,2.44,187,4.12,0.30,n
38,1712102400,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-03 00:00:00,284.63,284.05,284.63,284.63,1015,1015,987,85,0.00,95,2.51,192,4.47,NaN,n
39,1712113200,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2024-04-03 03:00:00,282.93,281.63,282.93,282.93,1014,1014,987,85,0.00,81,2.62,199,4.80,NaN,n

In [ ]:
# df4 = pd.concat([df1, df2], axis=1)

In [131]:
my_timestamp = pd.to_datetime(response.json()["list"][t]["dt_txt"])
print(my_timestamp.strftime("%d/%m %H:%M"), round((response.json()["list"][t]["main"]["temp"]-273.0),2))

02/04 18:00 13.39

In [132]:
# Testing

nb = len(response.json()["list"])
for t in range(nb):
  my_timestamp = pd.to_datetime(response.json()["list"][t]["dt_txt"])
  print(my_timestamp.strftime("%d/%m %H:%M"), round((response.json()["list"][t]["main"]["temp"]-273.0),2))

28/03 21:00 18.06
29/03 00:00 17.54
29/03 03:00 15.3
29/03 06:00 10.19
29/03 09:00 12.86
29/03 12:00 14.19
29/03 15:00 12.25
29/03 18:00 10.21
29/03 21:00 8.4
30/03 00:00 6.79
30/03 03:00 6.02
30/03 06:00 5.72
30/03 09:00 12.49
30/03 12:00 15.17
30/03 15:00 16.32
30/03 18:00 11.92
30/03 21:00 9.6
31/03 00:00 10.49
31/03 03:00 9.57
31/03 06:00 9.81
31/03 09:00 10.51
31/03 12:00 13.51
31/03 15:00 14.57
31/03 18:00 12.09
31/03 21:00 10.65
01/04 00:00 10.17
01/04 03:00 10.31
01/04 06:00 10.21
01/04 09:00 13.81
01/04 12:00 15.74
01/04 15:00 13.2
01/04 18:00 10.6
01/04 21:00 9.35
02/04 00:00 7.33
02/04 03:00 6.54
02/04 06:00 6.28
02/04 09:00 14.19
02/04 12:00 16.56
02/04 15:00 16.85
02/04 18:00 13.39

In [133]:
df_weather = pd.DataFrame(columns=["Site", "latitude", "longitude", ""])
df_weather

Empty DataFrame
Columns: [Site, latitude, longitude, ]
Index: []

In [135]:
url = "http://api.openweathermap.org/data/2.5/forecast"


for index, row in df.iterrows():
  if (index==5):
    break
  latitude = row['latitude']
  longitude = row['longitude']
  site = row['site']

  # print(latitude, longitude)

  params = {
    "lat" : latitude,
    "lon" : longitude,
    "appid" : openweathermap_key,
  }
  
  response = requests.get(url, params=params) 
  # list_tmp = [site, response.json()[0]["lat"], response.json()[0]["lon"]]
  # df.loc[len(df)] = list_tmp
  my_timestamp = pd.to_datetime(response.json()["list"][0]["dt_txt"])
  print(site, my_timestamp.strftime("%d/%m %H:%M"), round((response.json()["list"][t]["main"]["temp"]-273.0),2))

# df

Mont Saint Michel 28/03 21:00 9.91
St Malo 28/03 21:00 5.08
Bayeux 28/03 21:00 10.31
Le Havre 28/03 21:00 10.92
Rouen 28/03 21:00 10.6

* Aller lire : https://openweathermap.org/forecast5
* Comment faire un indice météo ?
* pop = proba de pluie etc.
* Faire un radar chart avec vent, proba pluie, soleil, temp... ?
* Voir comment récupérer les icones qui sont dans response.json()["list"]
  * https://openweathermap.org/weather-conditions
  * https://stackoverflow.com/questions/44177417/how-to-display-openweathermap-weather-icon




<img src="https://openweathermap.org/img/wn/01d@2x.png"/>
<img src="https://openweathermap.org/img/wn/02d@2x.png"/>
<img src="https://openweathermap.org/img/wn/03d@2x.png"/>

https://www.booking.com/searchresults.fr.html?ss=Paris&checkin=2024-04-02&checkout=2024-04-05&group_adults=2&no_rooms=1&group_children=0

In [19]:

import re

# latitude Paris = 48.5
# str = 'dsfs sdfsdf  sdfsdf data-atlas-latlng="49.27603159,-0.70172489" sdfsdf sdfs sdfsdfsdf'
str = "<a id=\"hotel_sidebar_static_map\" class=\"loc_block_link_underline_fix \nmap_static_zoom show_map map_static_hover jq_tooltip map_static_button_hoverstate maps-more-static-focus txp-fix-hover \n\" href=\"#map_opened-hotel_sidebar_static_map\" data-atlas-latlng=\"49.27603159,-0.70172489\" data-lang-for-url=\"fr\" data-action=\"hotel\" data-api-key=\"AIzaSyDXrqUc7k84GZ0W6P5sMFrKFMVIdN-Nd0w\" data-atlas-bbox=\"49.2580661691929,-0.729312459909215,49.2939970023391,-0.674137313879237\" style=\" height:200px; background: url(https://maps.googleapis.com/maps/api/staticmap?zoom=13&amp;language=fr&amp;channel=hotel&amp;key=AIzaSyDXrqUc7k84GZ0W6P5sMFrKFMVIdN-Nd0w&amp;size=264x200&amp;center=49.27603159,-0.70172489&amp;signature=vw0aiEsLvjH3HpPtTeyAhzDmgck=) center; \" data-source=\"map_thumbnail\" data-map-open-text=\"Retour \u00e0 l'\u00e9tablissement\" role=\"button\">\n<div class=\"txp-map-cta-wrap\">\n<button class=\"txp-map-cta bui-button bui-button--primary\" data-map-open-text=\"Retour \u00e0 l'\u00e9tablissement\" data-map-thumb-label>\n<span class=\"bui-button__text\">\nVoir sur la carte\n</span>\n</button>\n</div>\n<span class=\"map-thumb__marker--current\">\n<svg class=\"property-marker\" xmlns=\"http://www.w3.org/2000/svg\" viewbox=\"0 0 18 29\">\n<ellipse class=\"shadow\" fill=\"#000000\" fill-opacity=\"0.24\" cx=\"9\" cy=\"27\" rx=\"6\" ry=\"2\"></ellipse>\n<path class=\"pin\" d=\"M9,27 C7,27 0,16.9704016 0,9 C2.28269391e-16,4.02943725 4.02943725,0 9,0 C13.9705627,0 18,4.02943725 18,9 C18,16.9704016 11,27 9,27 Z M9,13 C11.209139,13 13,11.209139 13,9 C13,6.790861 11.209139,5 9,5 C6.790861,5 5,6.790861 5,9 C5,11.209139 6.790861,13 9,13 Z\"></path>\n</svg>\n</span>\n</a>"
numbers = re.findall('[+-]*\d+\.\d+', str)
# latitude = re.findall("\d+\.\d+", "Current Level: 13.4db.")
latitude = numbers[0]
longitude = numbers[1]
print(latitude)
print(longitude)

49.27603159
-0.70172489